### ISSUE TITLE
Issue witg rolling dices

### ISSUE THREAD

**Issue by Gildfx2** [MrLaki5/Backgammon-game#1]
First of all, great design! But I'm having trouble with rolling the dices, what to do? I mean what event is it listening to?

**Comment by MrLaki5** [comment]
Hey, I am glad that you like the design. Dices are being rolled with shaking the phone. That logic is situated [here](https://github.com/MrLaki5/Backgammon-game/blob/master/app/src/main/java/games/mrlaki5/backgammon/Players/Human.java#L37).

It is listening for the shake events, a method for that is [here](https://github.com/MrLaki5/Backgammon-game/blob/master/app/src/main/java/games/mrlaki5/backgammon/GameControllers/GameActivity.java#L360).

I haven't tried running the game since development, so hopefully, it is not something due to newer versions of Android and stuff getting deprecated...

**Comment by Gildfx2** [comment]
> 

It's working, good job. It didn't work at first because I ran it on emulator.

**Comment by MrLaki5** [comment]
Thanks, I am glad it works!
